from enum import Enum


class BatchStatus(str, Enum):
    NEW = "NEW"
    PREPARED = "PREPARED"
    TEXT_READY = "TEXT_READY"
    CLASSIFIED = "CLASSIFIED"
    FILLED_AUTO = "FILLED_AUTO"
    FILLED_REVIEWED = "FILLED_REVIEWED"
    VALIDATED = "VALIDATED"
    DONE = "DONE"
    FAILED = "FAILED"


class DocumentStatus(str, Enum):
    NEW = "NEW"
    TEXT_READY = "TEXT_READY"
    CLASSIFIED = "CLASSIFIED"
    FILLED_AUTO = "FILLED_AUTO"
    FILLED_REVIEWED = "FILLED_REVIEWED"
    FAILED = "FAILED"


class DocumentType(str, Enum):
    UNKNOWN = "UNKNOWN"
    EXPORT_DECLARATION = "EXPORT_DECLARATION"
    INVOICE = "INVOICE"
    # INVOICE = "invoice.json"
    PACKING_LIST = "PACKING_LIST"
    BILL_OF_LANDING = "BILL_OF_LANDING"
    PROFORMA = "PROFORMA"
    SPECIFICATION = "SPECIFICATION"
    PRICE_LIST_1 = "PRICE_LIST_1"
    PRICE_LIST_2 = "PRICE_LIST_2"
    QUALITY_CERTIFICATE = "QUALITY_CERTIFICATE"
    CERTIFICATE_OF_ORIGIN = "CERTIFICATE_OF_ORIGIN"
    VETERINARY_CERTIFICATE = "VETERINARY_CERTIFICATE"


class ValidationSeverity(str, Enum):
    OK = "ok"
    WARN = "warn"
    ERROR = "error"


